# Example TOML demonstrating randomizing/setting driver model parameters from TOML.
# These parameters can be set on the ego and dynamic vehicles.
  # Example: driver_model.lane_offset - To drive off centered.
  # Example: driver_model.speed_limit_ratio - To model vehicles driving over/under the speed limit
  # Example: driver_model.aggressiveness - To model overall aggressiveness of vehicle. # Controls speed limit ratio, following distance etc
  # Example: ref_traffic_model_vehicle.driving_state - 'parked', 'reverse', 'drive'

# This toml to cover parameters (lane_offset, slow_traffic and fast_traffic) only applied on non-ego.

[Assets]
root = "{/app/drivesim/defaultNucleusRoot}/"
sets = [
    "ego.toml",
    "dynamic_traffic_vehicles.toml",
]

# Parameters= "lane_offset, slow_traffic and fast_traffic"

[Events.config]
enable_script = true
enable_periodic = true
periodic_start_frame = 0
collisions_enabled = true
enable_ego_teleportation = false

[[Events.setup]]
type='EgoRand'
func='setup'
pop_name='ego'
asset_file='ego.toml'
asset_sel_type='index'
asset_sel=[0]
driver_model.lane_offset=true
driver_model.speed_limit_ratio=1
ref_traffic_model_vehicle.driving_state="parked"

[[Events.setup]]
type= 'VehicleRandDyn'
func= 'setup'
pop_name='offset_traffic_vehicles'
asset_file='dynamic_traffic_vehicles.toml'
asset_sel_type='index'
asset_sel=[0]
 
[[Events.setup]]
type= 'VehicleRandDyn'
func= 'setup'
pop_name='slow_traffic_vehicles'
asset_file='dynamic_traffic_vehicles.toml'
asset_sel_type='index'
asset_sel=[0]

[[Events.setup]]
type= 'VehicleRandDyn'
func= 'setup'
pop_name='fast_traffic_vehicles'
asset_file='dynamic_traffic_vehicles.toml'
asset_sel_type='index'
asset_sel=[0]

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_position'
pop_name='slow_traffic_vehicles'
region_center='ahead_ego'
region_diameter=30
shuffle_order=true
offset=0
driver_model.speed_limit_ratio=0.1

[[Events.setup]]
type='VehicleRandDyn'
func='set_pop_speed'
pop_name='slow_traffic_vehicles'
speed=20

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_position'
pop_name='fast_traffic_vehicles'
region_center='ahead_ego'
region_diameter=50
shuffle_order=true
offset=0
driver_model.speed_limit_ratio=0.4

[[Events.setup]]
type='VehicleRandDyn'
func='set_pop_speed'
pop_name='fast_traffic_vehicles'
speed=40

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_position'
pop_name='offset_traffic_vehicles'
region_center='ahead_ego'
region_diameter=40
shuffle_order=true
offset=0
driver_model.lane_offset=-3
driver_model.speed_limit_ratio=0.2

[[Events.setup]]
type='VehicleRandDyn'
func='set_pop_speed'
pop_name='offset_traffic_vehicles'
speed=10