from enum import Enum


class OmniModel(Enum):
    """Enum class containing model names for all window

    Args:
        Enum (Enum): _description_
    """

    main_toolbar_model = "MainToolBarModel"
    example_model = "ExampleModel"
    viewport_model = "ViewportModel"
    render_settings_model = "RenderSettingsModel"
    privacy_model = "PrivacyModel"
    stage_model = "StageModel"
    property_model = "PropertyModel"
    content_model = "ContentModel"
    materials_model = "MaterialsModel"
    assets_model = "AssetsModel"
    open_file_model = "OpenFileModel"
    save_file_as_model = "SaveFileAsModel"
    extensions_model = "ExtensionsModel"
    textures_model = "TexturesModel"
    movie_capture_model = "MovieCaptureModel"
    environments_model = "EnvironmentsModel"
    layer_model = "LayerModel"
    preference_model = "PreferenceModel"
    common_model = "CommonModel"
    sequencer_model = "SequencerModel"
    asset_store_model = "AssetStoreModel"
    live_session_model = "LiveSessionModel"
    landing_model = "LandingModel"
    welcome_to_ov_model = "WelcomeToOmniverseModel"
    welcome_screen_model = "WelcomeScreenModel"
    simple_share_model = "SimpleShareModel"
    timeline_model = "TimelineModel"
    script_editor_model = "ScriptEditorModel"
    hotkeys_model = "HotkeysModel"
    measure_model = "MeasureModel"
    view_toolbar_model = "ViewToolbarModel"
    usd_paths_model = "USDPathsModel"
    waypoint_model = "WaypointModel"
    tools_model = "ToolsModel"
    select_file_to_save_layout_model = "SelectFileToSaveLayout"
    ogc_map_tile_loader_model = "OGCMapTileLoaderModel"
    section_model = "SectionModel"
    markup_model = "MarkupModel"
    share_omniverse_usd_path_model = "ShareOmniverseUSDPathModel"
    about_model = "AboutModel"
    timeline_session_model = "TimelineSessionModel"
    add_new_search_path_model = "AddNewSearchPathModel"
    material_graph_model = "MaterialGraphModel"
    curve_editor_model = "CurveEditorModel"
    variant_presenter_model = "VariantPresenterModel"
    animgraph_model = "AnimGraphModel"
    physics_authoring_toolbar_model = "PhysicsAuthoringToolbarModel"
    turntable_model = "TurntableModel"
    message_dialog_model = "MessageDialogModel"
    props_physics_model = "PropsPhysicsModel"
    vehicles_ingest_model = "VehiclesIngestModel"
    simready_asset_studio_test_model = "SimreadyAssetStudioTestModel"
    map2sim_roads_content_generation_model = "Map2simRoadsContentGenerationModel"
    map2sim_barrier_presets_model = "Map2simBarrierPresetsModel"
    map2sim_pdg_tools_model = "Map2simPDGToolModel"
    simready_studio_edit_window_model = "SimreadyStudioEditModel"
    simready_studio_modebar_model = "SimreadyStudioModeBarModel"
    simready_studio_open_window_model = "SimreadyStudioOpenWindowModel"
    static_prop_ingest_model = "StaticPropIngestModel"
    select_file_model = "SelectFileModel"
    array_tool_model = "ArrayToolModel"
    export_markup_model = "ExportMarkupModel"
    scene_optimizer_model = "SceneOptimizerModel"
    drive_sim_maps_model = "DriveSimMapsModel"
    drive_sim_v2_maps_model = "DriveSimV2MapsModel"
    drive_sim_v2_scenario_editor_model = "DriveSimV2ScenarioEditorModel"
    drive_sim_scenario_editor_model = "DriveSimScenarioEditorModel"
    drive_sim_property_model = "DriveSimPropertyModel"
    drive_sim_scenario_parameter_model = "DriveSimScenarioParamterModel"
    drive_sim_scenario_action_model = "DriveSimScenarioActionModel"
    drive_sim_outliner_model = "DriveSimOutlinerModel"
    avatar_studio_model = "AvatarStudioModel"
    select_file_or_directory_model = "SelectFileOrDirectoryModel"
    load_definition_model = "LoadDefinitionModel"
    physics_demo_scenes_model = "PhysicsDemoScenesModel"
    physics_inspector_model = "PhysicsInspectorModel"
    zero_gravity_model = "ZeroGravityModel"
    wrapp_model = "WrappModel"
    actiongraph_model = "ActionGraphModel"
    asset_validator_model = "AssetValidatorModel"
    variant_editor_model = "VariantEditorModel"
    activity_model = "ActivityModel"
    farm_agent_model = "FarmAgentModel"
    farm_queue_model = "FarmQueueModel"
    drive_sim_sdg_model = "DriveSimSDGModel"
    model = "Model"