[Assets]
root = "{/app/drivesim/defaultNucleusRoot}/"
sets = [
    "ego.toml",
    "dynamic_traffic_vehicles.toml",
    "dynamic_traffic_large_vehicles.toml",
    "static_traffic_vehicles.toml"
]

[Events.config]
enable_script = true
enable_periodic = true
periodic_start_frame = 0
collisions_enabled = true
enable_ego_teleportation = false

[[Events.setup]]
type= 'VehicleRandDyn'
func= 'setup'
pop_name='traffic_vehicles'
asset_file='dynamic_traffic_vehicles.toml'
asset_sel_type='all'
asset_qty=1
#asset_sel_type='index'
#asset_sel=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

[[Events.setup]]
type= 'VehicleRandDyn'
func= 'setup'
pop_name='large_traffic_vehicles'
asset_file='dynamic_traffic_large_vehicles.toml'
asset_sel_type='index'
asset_sel=[0,1,2,3,4,5,6,7,8]
asset_qty=[2,2,2,1,2,2,2,2,2]

[[Events.setup]]
type= 'VehicleRandStat'
func= 'setup'
pop_name='parked_vehicles'
asset_file='static_traffic_vehicles.toml'
asset_sel_type='all'
asset_qty=10

## Sequential randomization is:
## Load map -> do randomization -> play
## Unlike non-sequential, no placement randomization occurs during simulation

[[Events.setup]]
type='EgoRand'
func='set_pop_speed'
pop_name='ego'
speed=15

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_speed'
pop_name='traffic_vehicles'
speed_range=[10, 15]

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_speed'
pop_name='large_traffic_vehicles'
speed_range=[10, 15]

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_position'
pop_name='traffic_vehicles'
region_center='surround_ego'
region_diameter=40
shuffle_order=true
offset=5
min_distance=10
num_placements='all'

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_position'
pop_name='large_traffic_vehicles'
region_center='ahead_ego'
region_diameter=30
shuffle_order=true
offset=5
min_distance=14
#num_placements=2
num_placements='all'

[[Events.setup]]
type='VehicleRandStat'
func='randomize_position'
region_diameter=45
pop_name='parked_vehicles'
surface_type='parking'
region_center='surround_ego' # 'ahead_ego', 'surround_ego', 'behind_ego'
orientation='mixed'  # 'forward', 'reverse', 'mixed'
num_placements='all'

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_color'
pop_name='traffic_vehicles'

[[Events.setup]]
type='VehicleRandDyn'
func='randomize_color'
pop_name='large_traffic_vehicles'

[[Events.setup]]
type='VehicleRandStat'
func='randomize_color'
pop_name='parked_vehicles'

# WEATHERRAND SETUP AND DEMO:
# Setting up events can be done one of two ways:
# If no preset_name is specified the Environment System defaults are populated
[[Events.setup]]
type='WorldRand.weather'
func='setup'

# Or if preset_name is specified, any existing preset name will be updated
# with the parameters passed as arguments
# WeatherRand setup define presets with 5 values in addition to preset_name:
# azimuth:[0,360] elevation:[-20,?] cloudiness:[0.0,1.0],road_wetness:[0.0,1.0], fog:[0.0,1.0]
# NOTE: Fog is only supported in PathTracing render mode

#[[Events.setup]]
#type='WorldRand.weather'
#func='setup'
#preset_name='_dawn_wet'
#azimuth=180
#elevation=0
#cloudiness=0.25
#road_wetness=1.0

[[Events.setup]]
type='WorldRand.weather'
func='setup'
preset_name='_noon_wet'
azimuth=180
elevation=10
cloudiness=0.25
road_wetness=0.5

[[Events.setup]]
type='WorldRand.weather'
func='setup'
preset_name='_stormday_wet'
azimuth=150
elevation=50
cloudiness=1.0
road_wetness=1.0
fog=1.0

[[Events.setup]]
type='WorldRand.weather'
func='setup'
preset_name='_afternoon_wet'
azimuth=270
elevation=50
cloudiness=0.5
road_wetness=1.0
fog=0.5

#[[Events.setup]]
#type='WorldRand.weather'
#func='setup'
#preset_name='_dawn_dry'
#azimuth=180
#elevation=0
#cloudiness=0.25
#road_wetness=0.0

[[Events.setup]]
type='WorldRand.weather'
func='setup'
preset_name='_noon_dry'
azimuth=180
elevation=10
cloudiness=0.25
road_wetness=0.0

[[Events.setup]]
type='WorldRand.weather'
func='setup'
preset_name='_stormday_dry'
azimuth=150
elevation=50
cloudiness=1.0
road_wetness=0.0

[[Events.setup]]
type='WorldRand.weather'
func='setup'
preset_name='_afternoon_dry'
azimuth=270
elevation=50
cloudiness=0.25
road_wetness=0.0

# Once defined, presets can be set in one of three ways:
# Either through randomize_environment, which selects from presets from a
# seeded psuedorandom sequence
# (called in setup here to start before frame 0)
[[Events.setup]]
type='WorldRand.weather'
#func='randomize_environment'
func='set_environment'
preset_name='_noon_wet'

## Currently, due to limitations with content python API and event scheduling,
## when turning on multiple lights in one func call, it may need to be repeated to take effect.
## This is why below, we execute light funcs multiple times in setup and on frame 0
[[Events.setup]]
type='EgoRand'
func='set_light'
light_type='head'
enable=true

[[Events.setup]]
type='VehicleRandDyn'
func='set_all_lights'
pop_name='traffic_vehicles'
enable=true

[[Events.setup]]
type='VehicleRandDyn'
func='set_all_lights'
pop_name='large_traffic_vehicles'
enable=true

[[Events.scripted.0]]
type='EgoRand'
func='set_light'
light_type='head'
enable=true

[[Events.scripted.0]]
type='VehicleRandDyn'
func='set_all_lights'
pop_name='traffic_vehicles'
enable=true

[[Events.scripted.0]]
type='VehicleRandDyn'
func='set_all_lights'
pop_name='large_traffic_vehicles'
enable=true

#### PERIODIC EVENTS ####

[[Events.scripted.2]]
type='VehicleRandDyn'
func='randomize_color'
pop_name='traffic_vehicles'

[[Events.periodic.2]]
type='VehicleRandDyn'
func='randomize_color'
pop_name='large_traffic_vehicles'

[[Events.periodic.2]]
type='VehicleRandStat'
func='randomize_color'
pop_name='parked_vehicles'

# Or through 'next_preset', which cycles to the next preset available
# Wrapping around when the preset dict end is reached.
# Set to happen every 20 frames
# NOTE: Each WeatherRand call is perf-heavy, so moderation is advised.
# Recommend no more often than every 15-30 frames depending on compute resources
#[[Events.periodic.20]]
#type='WorldRand.weather'
#func='next_preset'