[Assets]
root = '{/app/drivesim/defaultNucleusRoot}/'
sets = [
    'ego.toml',
    'static_traffic_vehicles.toml',
    'pedestrian.toml',
    'pedestrian_poses.toml',
]

[Events.config]
enable_script = true
enable_periodic = true
periodic_start_frame = 0
collisions_enabled = true
enable_ego_teleportation = true

[[Events.setup]]
type='EgoRand'
func='setup'
pop_name='ego'
asset_file='ego.toml'
asset_sel_type='index'
asset_sel=[0]
# spawn_pts=[[9, 4, 118]]

[[Events.setup]]
type= 'VehicleRandStat'
func= 'setup'
pop_name='parked_vehicles'
asset_file='static_traffic_vehicles.toml'
asset_sel_type='all'
asset_qty=1

[[Events.setup]]
type= 'VehicleRandStat'
func= 'setup'
pop_name='traffic_vehicles'
asset_file='static_traffic_vehicles.toml'
asset_sel_type='index'
asset_sel=[1,2]


#### PERIODIC EVENTS ####

[[Events.periodic.1]]
type='EgoRand'
func='place_along_road'
distance=10

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_position'
pop_name='parked_vehicles'
surface_type='parking'
region_center='ahead_ego'
orientation='mixed'  # 'forward', 'reverse', 'mixed'

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_position'
pop_name='traffic_vehicles'
region_center='ahead_ego'
region_diameter=100


