[Assets]
root = "{/app/drivesim/defaultNucleusRoot}/"
sets = [
    "ego.toml",
    "road_signs.toml",
    "static_traffic_vehicles.toml",
    "static_public_vehicles.toml",
    "cones.toml",
    "props_road_debris.toml",
    'pedestrian.toml',
    'pedestrian_poses.toml',
]

[Events.config]
enable_script = true
enable_periodic = true
periodic_start_frame = 0
collisions_enabled = true
enable_ego_teleportation = true

[[Events.setup]]
type='EgoRand'
func='setup'
pop_name='ego'
asset_file='ego.toml'
asset_sel_type='index'
asset_sel=[0]
# spawn_pts=[[9, 4, 118]]


[[Events.setup]]
type='PropStatic'
func='setup'
pop_name='debris'
asset_file='props_road_debris.toml'
asset_sel_type='range'
asset_sel=[3,6]

[[Events.setup]]
type='PropStatic'
func='setup'
pop_name='traffic_cones'
asset_file='cones.toml'
asset_sel_type='index'
asset_sel=[8]

[[Events.setup]]
type= 'VehicleRandStat'
func= 'setup'
pop_name='parked_vehicles'
asset_file='static_traffic_vehicles.toml'
asset_sel_type='range'
asset_sel=[0,14]

[[Events.setup]]
type='PedestrianRand'
func='setup'
pop_name='pedestrian'
asset_file='pedestrian.toml'
asset_sel_type='range'
asset_sel=[0,9]
asset_qty=1

[[Events.setup]]
type='PedestrianRand'
func='setup_pose'
pop_name='pedestrian_pose'
asset_file='pedestrian_poses.toml'
asset_sel_type='all'

#### PERIODIC EVENTS ####

[[Events.periodic.1]]
type='EgoRand'
func='place_along_road'
distance=10

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_position'
pop_name='parked_vehicles'
surface_type='parking'
region_center='ahead_ego'
orientation='mixed'  # 'forward', 'reverse', 'mixed'

[[Events.periodic.20]]
type='VehicleRandStat'
func='randomize_color'
pop_name='parked_vehicles'

[[Events.periodic.1]]
type='PropStatic'
func='randomize_position'
pop_name='debris'
offset=5

[[Events.periodic.1]]
type='PropStatic'
func='randomize_position'
pop_name='traffic_cones'

[[Events.periodic.1]]
type='PedestrianRand'
func='randomize_position'
pop_name='pedestrian'
region_center='ahead_ego'

[[Events.periodic.1]]
type='PedestrianRand'
func='randomize_pose'
pop_name_ped='pedestrian'
pop_name_pose='pedestrian_pose'

[[Events.periodic.1]]
type='PedestrianRand'
func='randomize_clothing'
pop_name='pedestrian'
