name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.13

      - name: Verify Python and dependencies
        run: |
          echo "Using Python version:"
          python --version
          echo "Installed dependencies:"
          pip list

      - name: Check required dependencies
        run: |
          missing=0
          for pkg in pytest toml numpy pandas; do
            if ! python -c "import $pkg" 2>/dev/null; then
              echo "❌ Missing dependency: $pkg"
              missing=1
            fi
          done
          if [ $missing -eq 1 ]; then
            echo "Some dependencies are missing. Please install them on the runner."
            exit 1
          fi
          echo "✅ All required dependencies are available."

      - name: Run tests
        run: |
          python -m pytest