name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Python version
        shell: powershell
        run: python --version

      - name: Run tests
        shell: powershell
        run: python main_runner.py map2sim_asset_mapping_table.toml --component MAP2SIM
