name: Map2sim Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Python version
        run: |
          echo "Using Python version:"
          python --version
          echo "Python path:"
          where python

      - name: Run MAP2SIM tests
        run: |
          # echo "▶️ Running test: map2sim_asset_mapping_table"
          # python main_runner.py map2sim_asset_mapping_table.toml --component MAP2SIM

          # echo "▶️ Running test: map2sim_map_preprocessing"
          # python main_runner.py map2sim_map_preprocessing.toml --component MAP2SIM

          echo "▶️ Running test: map2sim_terrain_elevation_hint"
          python main_runner.py map2sim_terrain_elevation_hint.toml --component MAP2SIM

      - name: Upload test outputs
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs
          path: Outputs/
          retention-days: 7